### ISSUE TITLE
Few Images size increased after converting to WebP

### ISSUE THREAD

**Issue by jhasuraj01** [devscollab/pcet-covid-task-force#72]
images
- Centralhelpdesk.png (39.25 KB) --> Centralhelpdesk.webp (43.51 KB)
- TechnicalSupport.png (32.43 KB) --> TechnicalSupport.webp (37.81 KB)

**Comment by tejasmorkar** [comment]
We already have the @ImgBotApp that optimizes all the images for us. So all the PNGs were already optimized for the web. We will revert to the previous ones for images with such issues.
